### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by Hunter-Thompson** [infracloudio/botkube#428]
https://www.botkube.io/installation/mattermost/

I followed this tutorial step by step, and when deploying it, it fails.

I am deploying using the `kubectl` option.

```
INFO[2020-11-04T11:12:14Z] Registering the filter ImageTagChecker
INFO[2020-11-04T11:12:14Z] Registering the filter IngressValidator
INFO[2020-11-04T11:12:14Z] Registering the filter NamespaceChecker
INFO[2020-11-04T11:12:14Z] Registering the filter NodeEventsChecker
INFO[2020-11-04T11:12:14Z] Registering the filter ObjectAnnotationChecker
INFO[2020-11-04T11:12:14Z] Registering the filter PodLabelChecker
INFO[2020-11-04T11:12:14Z] Starting controller
INFO[2020-11-04T11:12:14Z] Starting mattermost bot
INFO[2020-11-04T11:12:14Z] Starting upgrade notifier
INFO[2020-11-04T11:12:14Z] BotKube connected to Mattermost!
INFO[2020-11-04T11:12:22Z] Allowed Events - map[{Resource:apps/v1/daemonsets Namespace:all EventType:create}:true {Resource:apps/v1/daemonsets Namespace:all EventType:delete}:true {Resource:apps/v1/daemonsets Namespace:all EventType:error}:true {Resource:apps/v1/daemonsets Namespace:all EventType:update}:true {Resource:apps/v1/deployments Namespace:all EventType:create}:true {Resource:apps/v1/deployments Namespace:all EventType:delete}:true {Resource:apps/v1/deployments Namespace:all EventType:error}:true {Resource:apps/v1/deployments Namespace:all EventType:update}:true {Resource:apps/v1/statefulsets Namespace:all EventType:create}:true {Resource:apps/v1/statefulsets Namespace:all EventType:delete}:true {Resource:apps/v1/statefulsets Namespace:all EventType:error}:true {Resource:apps/v1/statefulsets Namespace:all EventType:update}:true {Resource:batch/v1/jobs Namespace:all EventType:create}:true {Resource:batch/v1/jobs Namespace:all EventType:delete}:true {Resource:batch/v1/jobs Namespace:all EventType:error}:true {Resource:batch/v1/jobs Namespace:all EventType:update}:true {Resource:networking.k8s.io/v1beta1/ingresses Namespace:all EventType:create}:true {Resource:networking.k8s.io/v1beta1/ingresses Namespace:all EventType:delete}:true {Resource:networking.k8s.io/v1beta1/ingresses Namespace:all EventType:error}:true {Resource:rbac.authorization.k8s.io/v1/clusterrolebindings Namespace:all EventType:create}:true {Resource:rbac.authorization.k8s.io/v1/clusterrolebindings Namespace:all EventType:delete}:true {Resource:rbac.authorization.k8s.io/v1/clusterrolebindings Namespace:all EventType:error}:true {Resource:rbac.authorization.k8s.io/v1/clusterroles Namespace:all EventType:create}:true {Resource:rbac.authorization.k8s.io/v1/clusterroles Namespace:all EventType:delete}:true {Resource:rbac.authorization.k8s.io/v1/clusterroles Namespace:all EventType:error}:true {Resource:rbac.authorization.k8s.io/v1/rolebindings Namespace:all EventType:create}:true {Resource:rbac.authorization.k8s.io/v1/rolebindings Namespace:all EventType:delete}:true {Resource:rbac.authorization.k8s.io/v1/rolebindings Namespace:all EventType:error}:true {Resource:rbac.authorization.k8s.io/v1/roles Namespace:all EventType:create}:true {Resource:rbac.authorization.k8s.io/v1/roles Namespace:all EventType:delete}:true {Resource:rbac.authorization.k8s.io/v1/roles Namespace:all EventType:error}:true {Resource:v1/configmaps Namespace:all EventType:create}:true {Resource:v1/configmaps Namespace:all EventType:delete}:true {Resource:v1/configmaps Namespace:all EventType:error}:true {Resource:v1/namespaces Namespace:all EventType:create}:true {Resource:v1/namespaces Namespace:all EventType:delete}:true {Resource:v1/namespaces Namespace:all EventType:error}:true {Resource:v1/nodes Namespace:all EventType:create}:true {Resource:v1/nodes Namespace:all EventType:delete}:true {Resource:v1/nodes Namespace:all EventType:error}:true {Resource:v1/persistentvolumeclaims Namespace:all EventType:create}:true {Resource:v1/persistentvolumeclaims Namespace:all EventType:delete}:true {Resource:v1/persistentvolumeclaims Namespace:all EventType:error}:true {Resource:v1/persistentvolumes Namespace:all EventType:create}:true {Resource:v1/persistentvolumes Namespace:all EventType:delete}:true {Resource:v1/persistentvolumes Namespace:all EventType:error}:true {Resource:v1/pods Namespace:all EventType:create}:true {Resource:v1/pods Namespace:all EventType:delete}:true {Resource:v1/pods Namespace:all EventType:error}:true {Resource:v1/services Namespace:all EventType:create}:true {Resource:v1/services Namespace:all EventType:delete}:true {Resource:v1/services Namespace:all EventType:error}:true]
INFO[2020-11-04T11:12:22Z] Allowed UpdateEvents - map[{Resource:apps/v1/daemonsets Namespace:all}:{Fields:[spec.template.spec.containers[*].image status.numberReady] IncludeDiff:true} {Resource:apps/v1/deployments Namespace:all}:{Fields:[spec.template.spec.containers[*].image status.availableReplicas] IncludeDiff:true} {Resource:apps/v1/statefulsets Namespace:all}:{Fields:[spec.template.spec.containers[*].image status.readyReplicas] IncludeDiff:true} {Resource:batch/v1/jobs Namespace:all}:{Fields:[spec.template.spec.containers[*].image status.conditions[*].type] IncludeDiff:true}]
INFO[2020-11-04T11:12:31Z] AllowedKubectlResourceMap - map[daemonsets:true deployments:true namespaces:true nodes:true pods:true statefulsets:true storageclasses:true]
INFO[2020-11-04T11:12:31Z] AllowedKubectlVerbMap - map[api-resources:true api-versions:true auth:true cluster-info:true describe:true diff:true explain:true get:true logs:true top:true]
INFO[2020-11-04T11:12:31Z] KindResourceMap - map[apiservice:apiservices binding:bindings certificate:certificates certificaterequest:certificaterequests certificatesigningrequest:certificatesigningrequests challenge:challenges clusterissuer:clusterissuers clusterrole:clusterroles clusterrolebinding:clusterrolebindings componentstatus:componentstatuses configmap:configmaps controllerrevision:controllerrevisions cronjob:cronjobs csidriver:csidrivers csinode:csinodes customresourcedefinition:customresourcedefinitions daemonset:daemonsets deployment:deployments endpoints:endpoints endpointslice:endpointslices eniconfig:eniconfigs event:events horizontalpodautoscaler:horizontalpodautoscalers ingress:ingresses ingressclass:ingressclasses issuer:issuers job:jobs lease:leases limitrange:limitranges localsubjectaccessreview:localsubjectaccessreviews mutatingwebhookconfiguration:mutatingwebhookconfigurations namespace:namespaces networkpolicy:networkpolicies node:nodes order:orders persistentvolume:persistentvolumes persistentvolumeclaim:persistentvolumeclaims pod:pods poddisruptionbudget:poddisruptionbudgets podsecuritypolicy:podsecuritypolicies podtemplate:podtemplates priorityclass:priorityclasses replicaset:replicasets replicationcontroller:replicationcontrollers resourcequota:resourcequotas role:roles rolebinding:rolebindings runtimeclass:runtimeclasses sealedsecret:sealedsecrets secret:secrets securitygrouppolicy:securitygrouppolicies selfsubjectaccessreview:selfsubjectaccessreviews selfsubjectrulesreview:selfsubjectrulesreviews service:services serviceaccount:serviceaccounts statefulset:statefulsets storageclass:storageclasses subjectaccessreview:subjectaccessreviews targetgroupbinding:targetgroupbindings tokenreview:tokenreviews validatingwebhookconfiguration:validatingwebhookconfigurations volumeattachment:volumeattachments]
INFO[2020-11-04T11:12:31Z] ShortnameResourceMap - map[cert:certificates certs:certificates cj:cronjobs cm:configmaps cr:certificaterequests crd:customresourcedefinitions crds:customresourcedefinitions crs:certificaterequests cs:componentstatuses csr:certificatesigningrequests deploy:deployments ds:daemonsets ep:endpoints ev:events hpa:horizontalpodautoscalers ing:ingresses limits:limitranges netpol:networkpolicies no:nodes ns:namespaces pc:priorityclasses pdb:poddisruptionbudgets po:pods psp:podsecuritypolicies pv:persistentvolumes pvc:persistentvolumeclaims quota:resourcequotas rc:replicationcontrollers rs:replicasets sa:serviceaccounts sc:storageclasses sgp:securitygrouppolicies sts:statefulsets svc:services]
INFO[2020-11-04T11:12:31Z] Registering resource lifecycle informer
INFO[2020-11-04T11:12:31Z] Adding informer for resource:v1/pods
INFO[2020-11-04T11:12:31Z] Adding informer for resource:v1/services
INFO[2020-11-04T11:12:31Z] Adding informer for resource:apps/v1/deployments
INFO[2020-11-04T11:12:31Z] Adding informer for resource:apps/v1/statefulsets
INFO[2020-11-04T11:12:31Z] Adding informer for resource:networking.k8s.io/v1beta1/ingresses
INFO[2020-11-04T11:12:31Z] Adding informer for resource:v1/nodes
INFO[2020-11-04T11:12:31Z] Adding informer for resource:v1/namespaces
INFO[2020-11-04T11:12:31Z] Adding informer for resource:v1/persistentvolumes
INFO[2020-11-04T11:12:31Z] Adding informer for resource:v1/persistentvolumeclaims
INFO[2020-11-04T11:12:31Z] Adding informer for resource:v1/configmaps
INFO[2020-11-04T11:12:31Z] Adding informer for resource:apps/v1/daemonsets
INFO[2020-11-04T11:12:31Z] Adding informer for resource:batch/v1/jobs
INFO[2020-11-04T11:12:31Z] Adding informer for resource:rbac.authorization.k8s.io/v1/roles
INFO[2020-11-04T11:12:31Z] Adding informer for resource:rbac.authorization.k8s.io/v1/rolebindings
INFO[2020-11-04T11:12:31Z] Adding informer for resource:rbac.authorization.k8s.io/v1/clusterrolebindings
INFO[2020-11-04T11:12:31Z] Adding informer for resource:rbac.authorization.k8s.io/v1/clusterroles
INFO[2020-11-04T11:12:31Z] Registering kubernetes events informer for types: warning
INFO[2020-11-04T11:12:31Z] Registering kubernetes events informer for types: normal
INFO[2020-11-04T11:12:31Z] Registering watcher on configfile /config/resource_config.yaml
panic: runtime error: index out of range [0] with length 0

goroutine 61 [running]:
github.com/infracloudio/botkube/pkg/bot.MMBot.getUser(0xc000358500, 0x1a, 0xc0003fb3b0, 0x9, 0xc0003fb3c0, 0xf, 0xc0003fadf0, 0x7, 0x1, 0xc0003583e0, ...)
	/app/pkg/bot/mattermost.go:212 +0x199
github.com/infracloudio/botkube/pkg/bot.MMBot.listen(0xc000358500, 0x1a, 0xc0003fb3b0, 0x9, 0xc0003fb3c0, 0xf, 0xc0003fadf0, 0x7, 0x1, 0xc0003583e0, ...)
	/app/pkg/bot/mattermost.go:245 +0x265
github.com/infracloudio/botkube/pkg/bot.(*MMBot).Start.func1(0xc0004a73b0)
	/app/pkg/bot/mattermost.go:125 +0xef
created by github.com/infracloudio/botkube/pkg/bot.(*MMBot).Start
	/app/pkg/bot/mattermost.go:113 +0x42a
```

I get a notification in my channel that the bot started so the connection to MM is not the problem.

>...and now my watch begins for cluster 'SC-Util'!

**Comment by Hunter-Thompson** [comment]
I believe I was getting this error because I didn't use the username `botkube` in Mattermost. when I changed the name to `botkube` it started working
