### ISSUE TITLE
[BUG] Panic on partial command

### ISSUE THREAD

**Issue by disconn3ct** [infracloudio/botkube#515]
**Describe the bug**
Botkube v0.12.1 crashes on incomplete commands

**To Reproduce**
1. Send `@botkube explain` as an allowed command from discord, with no arguments

**Expected behavior**
An error message or kubectl help message:
`error: You must specify the type of resource to explain. Use "kubectl api-resources" for a complete list of supported resources.`

**Screenshots**
```
E0821 13:26:24.099247       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.5/tools/cache/reflector.go:167: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
panic: runtime error: index out of range [1] with length 1

goroutine 872 [running]:
github.com/infracloudio/botkube/pkg/execute.(*DefaultExecutor).Execute(0x4000b63f80, 0x4000b63f80, 0x17)
	/go/src/github.com/infracloudio/botkube/pkg/execute/executor.go:195 +0x898
github.com/infracloudio/botkube/pkg/bot.(*discordMessage).HandleMessage(0x40007dbf40, 0x4000320d80)
	/go/src/github.com/infracloudio/botkube/pkg/bot/discord.go:123 +0x2fc
github.com/infracloudio/botkube/pkg/bot.(*DiscordBot).Start.func1(0x4000227900, 0x400009ad78)
	/go/src/github.com/infracloudio/botkube/pkg/bot/discord.go:82 +0x64
github.com/bwmarrin/discordgo.messageCreateEventHandler.Handle(0x400003a010, 0x4000227900, 0x13ce6a0, 0x400009ad78)
	/go/pkg/mod/github.com/bwmarrin/discordgo@v0.20.3/eventhandlers.go:497 +0x4c
created by github.com/bwmarrin/discordgo.(*Session).handle
	/go/pkg/mod/github.com/bwmarrin/discordgo@v0.20.3/event.go:171 +0xf4
```

**Additional context**

**Comment by PrasadG193** [comment]
Hey @disconn3ct, I think this is already fixed in the v0.12.2 release. Could you please upgrade BotKube and confirm?
