### ISSUE TITLE
[BUG] crashloop for mattermost bot on new deploy

### ISSUE THREAD

**Issue by hijak** [infracloudio/botkube#87]
**Describe the bug**
I am unable to use botkube with mattermost, am facing the following error

**To Reproduce**
i have tried deploying from the helm chart and via the yaml file. all needed config for mattermost is configured correctly

```
INFO[2019-05-09T08:37:29Z] Allowed Events - map[{Resource:clusterrole Namespace:all}:true {Resource:configmap Namespace:all}:true {Resource:daemonset Namespace:all}:true {Resource:deployment Namespace:all}:true {Resource:ingress Namespace:all}:true {Resource:job Namespace:all}:true {Resource:namespace Namespace:all}:true {Resource:node Namespace:all}:true {Resource:persistentvolume Namespace:all}:true {Resource:persistentvolumeclaim Namespace:all}:true {Resource:pod Namespace:all}:true {Resource:role Namespace:all}:true {Resource:rolebinding Namespace:all}:true {Resource:secret Namespace:all}:true {Resource:service Namespace:all}:true]
INFO[2019-05-09T08:37:29Z] Starting controller
INFO[2019-05-09T08:37:29Z] Starting mattermost bot
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x115de22]

goroutine 52 [running]:
github.com/infracloudio/botkube/vendor/github.com/mattermost/mattermost-server/model.(*WebSocketClient).Listen.func1.1(0x0)
	/go/src/github.com/infracloudio/botkube/vendor/github.com/mattermost/mattermost-server/model/websocket_client.go:101 +0x22
panic(0x1314c20, 0x2322130)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/infracloudio/botkube/vendor/github.com/mattermost/mattermost-server/model.(*WebSocketClient).Listen.func1(0x0)
	/go/src/github.com/infracloudio/botkube/vendor/github.com/mattermost/mattermost-server/model/websocket_client.go:109 +0x64
created by github.com/infracloudio/botkube/vendor/github.com/mattermost/mattermost-server/model.(*WebSocketClient).Listen
	/go/src/github.com/infracloudio/botkube/vendor/github.com/mattermost/mattermost-server/model/websocket_client.go:99 +0x3f
```

**Comment by hijak** [comment]
oh also my mattermost server has valid letsencrypt cert referfencing other issue

**Comment by hijak** [comment]
Hi

i have managed to get this working by setting the mattermost url to be the internal dns name with in the cluster. Im guessing it has something to do with mattermost being behind something

also ive noticed that the attatchments in mattermost are not using correct colors, as far as i know mattermost cannot interpret `danger` and `primary` type colors and you have to use hex

**Comment by PrasadG193** [comment]
Hey @hijak,
What is the version of Mattermost you are using?

**Comment by hijak** [comment]
Mattermost Version: 5.10.0

**Comment by mugdha-adhav** [comment]
Hi @hijak,
A pull request #83 is already created for fixing the issue and we are working on it.
